
development:
  adapter: mysql2
  database: swchd_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: swchd_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: swchd_production
  username: root
  password: 
  encoding: utf8

